### ISSUE TITLE
Saudações, irmão! Sobre o seu settings.__init__.py. Podes me tirar uma dúvida?

### ISSUE THREAD

**Issue by MatheusL3** [toticavalcanti/django_course#1]
Sou dev PHP e estou migrando pra Django agora, gostei muito do seu método de dois arquivos pras configurações do projeto, no PHP eu sempre fiz de forma semelhante. Entretanto, fiquei sem entender uma parte, podes me esclarecer?
Dentro do seu **settings.\__\__init\__\__.py**, você importa um arquivo **.local**, Do que se trata?

**try:
     from .local import *
except:
     pass**
     
Estou muito agradecido!

**Comment by toticavalcanti** [comment]
Opa Matheur, blz?
O __init__​​.py é para que a pasta settings seja um módulo, o __init__.py dentro de um subdiretório é sempre a primeira coisa a ser executada quando um módulo dentro deste subdiretório for chamado.

Dentro dele temos o que você perguntou, o que é .local? E porque ele tá aí?

from .base import *

from .production import *

try:
    from .local import *
except:
    pass

O .base importa o base.py dessa mesma pasta, que é o arquivo de configuração pra rodar no servidor local, o .production importa o production.py, que é a configuração para produção.
Agora, o  .local, como ele não existe, ou seja, não temos um local.py na pasta, a execução então cai no except, que tem um pass, ou seja, não faz nada, não importa nada do local.py até porque ele não existe.

Você pode usar esse try/catch para fazer os imports dentro, e caso haja algum problema, você trata no except.

Nesse caso acima, se o base.py existisse na pasta, ele importaria tudo dele e não cairia no except.

Vlw Matheus.

\o/ 😉
Toti

________________________________
De: Matheus L3 <notifications@github.com>
Enviado: domingo, 17 de janeiro de 2021 08:07
Para: toticavalcanti/django_course <django_course@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [toticavalcanti/django_course] Saudações, irmão! Sobre o seu settings.__init__.py. Podes me tirar uma dúvida? (#1)


Sou dev PHP e estou migrando pra Django agora, gostei muito do seu método de dois arquivos pras configurações do projeto, no PHP eu sempre fiz de forma semelhante. Entretanto, fiquei sem entender uma parte, podes me esclarecer?
Dentro do seu settings.__init__.py, você importa um arquivo .local, Do que se trata?

try:
from .local import *
except:
pass

Estou muito agradecido!

**Comment by MatheusL3** [comment]
Valeeeeeuu! ;D
